export enum Types {
   ON_DROP ='ON_DROP',
   ON_DRAG_ENTER = 'ON_DRAG_ENTER',
   ON_DRAG_LEAVE = 'ON_DRAG_LEAVE',
   SHOW_SIZE_SELECTION ='SHOW_SIZE_SELECTION',
   ON_SIZE_SELECT = 'ON_SIZE_SELECT',
   UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
}

